### ISSUE TITLE
Issues with S3 download commands

### ISSUE THREAD

**Issue by nmra-abarthmaron** [broadinstitute/2022_PERISCOPE#23]
I found that using at least some of the download commands (e.g., the ones [here](https://github.com/broadinstitute/2022_PERISCOPE/tree/main/Profile_Aggregation)) were not working for me.

Apologies if this issue is specific to me, but I found that adding wildcards at the beginning of the include strings helped solve the issue. (which could be due to hidden characters or filepath concatenation?)
e.g.:
`"*20210422_6W_CP257_guide_normalized_feature_select_median_merged_ALLBATCHES___*"`
instead of:
`"20210422_6W_CP257_guide_normalized_feature_select_median_merged_ALLBATCHES___*"`

I also noticed a typo in the A549 aggregated profile csvs. They are 20200805_A549_WG_Screen_guide_normalized_feature_select_**merged_median**_ rather than 20200805_A549_WG_Screen_guide_normalized_feature_select_**median_merged**_

thanks!

**Comment by ErinWeisbart** [comment]
Thanks for catching those! 

We re-organized our files a bit after writing documentation and apparently missed updating a couple paths. I've updated the READMEs to reflect the errors you caught.

File names should be consistently `median_merged` so I've updated the notebook and file paths in S3 to match.

**Comment by nmra-abarthmaron** [comment]
np, thanks for updating! overall the documentation and organization is super nice and easy to follow!
